### ISSUE TITLE
New Helm V2A - Maskrom Mode Process

### ISSUE THREAD

**Issue by stealthcypher** [HelmSecure/armbian-images#8]
Hi there!  I have the v1 helm and purchased the v2 helm to serve as a new mail server (to be configured for that later).  I have not registered or configured the new v2 helm I just received and went right to the Maskrom steps.  Unfortunately, I seem not to be able to detect it as a usb device.  I've followed the steps and experienced the following:

1. Power device.  
2. Wait until front light flashes Green and Blue consistently
3. Hold power button for 25 seconds (front light stops)
4. Remove power cable, Release button
5. Press power button, replace power cable
6. Release power button after 6 seconds
7. Front light does not start, NIC card flashes green/yellow
8. Can not detect USB device on Mac, or by proxy, my ubuntu VirtualBox VM.

For new devices, never registered or configured, are there any additional steps that need to occur?

Any guidance would be helpful and appreciated!

**Comment by ivahos** [comment]
After having some problems with the same, I found this procedure to be the most reliable way to get the unit into flash mode:
1 While the unit is powered on and connected to wired ethernet (so that you can use the lights on the ethernet port to tell when the unit powers down), start pressing the power button until the lights on the ethernet ports shut off. 

2 While you still press the power button, remove the power cable and reinsert it after a second.

3  After 6 seconds, release the power button. The lights on the ethernet plug should NOT turn back on. If they do, start over with step 1.

4 Only the leftmost USB-C plug, viewed from behind, works for flashing the unit.  On a mac, use the "System Information" app to check that you can see the device under the USB tab. Remember, you can press command+r to refresh the information in this app.

**Comment by stealthcypher** [comment]
Thanks for chiming in @ivahos !  A few iterations, and I am now able to see the usb device, but can't quite catch it in flash mode.

Here's what I see on the Mac:
<img width="475" alt="Screen Shot 2022-12-27 at 16 37 51" src="https://user-images.githubusercontent.com/61719047/209740343-ecf5ce62-5436-493d-ad2a-4bee371c49b8.png">

Here's what I see in my Ubuntu VM:
![VirtualBox_StealthCypher_27_12_2022_16_39_20](https://user-images.githubusercontent.com/61719047/209740298-44df3700-3bdc-4577-a511-ea32f77c1945.png)

**Comment by dsigurds** [comment]
Are you forwarding the USB device to from the MacOS host to the virtual machine?  That's usually an option in the virtual machine software settings.
